
FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir --extra-index-url https://download.pytorch.org/whl/cpu -r requirements.txt

# bcrypt bugfix
RUN sed -i 's/version = _bcrypt.__about__.__version__/version = _bcrypt.__version__/' /usr/local/lib/python3.12/site-packages/passlib/handlers/bcrypt.py

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]