"""Добавил в таблицу историй путь до изображений

Revision ID: 220ffec67d39
Revises: 68a3f92554eb
Create Date: 2025-03-12 17:38:50.249517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '220ffec67d39'
down_revision: Union[str, None] = '68a3f92554eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historys', sa.Column('image_path', sa.String(), nullable=False), schema='plant_diseases')
    op.create_unique_constraint(None, 'historys', ['image_path'], schema='plant_diseases')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'historys', schema='plant_diseases', type_='unique')
    op.drop_column('historys', 'image_path', schema='plant_diseases')
    # ### end Alembic commands ###
