"""Тест

Revision ID: 5014b1ccb12d
Revises: bf6c75fbb20e
Create Date: 2025-03-12 19:59:19.165075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5014b1ccb12d'
down_revision: Union[str, None] = 'bf6c75fbb20e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
