"""create users role

Revision ID: 68a3f92554eb
Revises: bfb12ac3b6f3
Create Date: 2025-03-02 17:07:30.431228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68a3f92554eb'
down_revision: Union[str, None] = 'bfb12ac3b6f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_user', sa.Boolean(), server_default=sa.text('true'), nullable=False), schema='plant_diseases')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False), schema='plant_diseases')
    op.add_column('users', sa.Column('is_super_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False), schema='plant_diseases')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_super_admin', schema='plant_diseases')
    op.drop_column('users', 'is_admin', schema='plant_diseases')
    op.drop_column('users', 'is_user', schema='plant_diseases')
    # ### end Alembic commands ###
