"""d

Revision ID: 93884ab33834
Revises: db007da3fc6a
Create Date: 2025-04-22 19:54:26.073250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93884ab33834'
down_revision: Union[str, None] = 'db007da3fc6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('historys_image_path_key', 'historys', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('historys_image_path_key', 'historys', ['image_path'])
    # ### end Alembic commands ###
