"""Fix primary key in history

Revision ID: f34b46fa4f2e
Revises: 5014b1ccb12d
Create Date: 2025-03-12 20:11:43.299861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f34b46fa4f2e'
down_revision: Union[str, None] = '5014b1ccb12d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
